name: sportmate
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages with null safety support
  firebase_core: ^2.16.0
  firebase_auth: ^4.8.1
  firebase_auth_web: ^5.1.1
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.3.2
  firebase_app_check: ^0.2.2
  firebase_storage_web: ^3.6.23
  shared_preferences: ^2.1.0

  # Additional dependencies
  google_maps_flutter: ^2.2.0
  share_plus: ^6.3.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  intl: ^0.20.0
  video_player: ^2.5.0 
  http: ^1.2.2
  http_parser: ^4.0.1
  flutter_dotenv: ^5.0.2
  google_mobile_ads: ^3.0.0
  firebase_messaging: ^14.9.4
  flutter_launcher_icons: ^0.11.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "/home/test/Downloads/appstore.png"  # Path to your app icon image

flutter:
  uses-material-design: true
assets:
    - assets/images/sports_logo.png